import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const exportDashboardPDF = ({
  adminName = "Administrator",
  statistics = {},
  activities = [],
}) => {
  const doc = new jsPDF();

  const generatedDate = new Date().toLocaleString();

  // ===========================
  // Header
  // ===========================

  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235);
  doc.text("VivaPartner", 14, 20);

  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("Dashboard Report", 14, 30);

  doc.setFontSize(11);

  doc.text(`Admin : ${adminName}`, 14, 40);
  doc.text(`Generated : ${generatedDate}`, 14, 47);

  // ===========================
  // Statistics
  // ===========================

  autoTable(doc, {
    startY: 58,

    head: [["Statistics", "Count"]],

    body: [
      ["Teachers", statistics.teachers || 0],
      ["Departments", statistics.departments || 0],
      ["Subjects", statistics.subjects || 0],
      ["Classes", statistics.classes || 0],
    ],

    theme: "grid",

    headStyles: {
      fillColor: [37, 99, 235],
    },
  });

  // ===========================
  // Recent Activities
  // ===========================

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 12,

    head: [["Activity", "Date"]],

    body:
      activities.length > 0
        ? activities.map((item) => [
            item.title,
            new Date(item.createdAt).toLocaleString(),
          ])
        : [["No Recent Activity", "-"]],

    theme: "striped",

    headStyles: {
      fillColor: [16, 185, 129],
    },
  });

  // ===========================
  // Footer
  // ===========================

  doc.setFontSize(10);

  doc.text(
    "Generated by VivaPartner Admin Dashboard",
    14,
    doc.internal.pageSize.height - 12
  );

  const date = new Date().toLocaleDateString("en-GB").replace(/\//g, "-");

  doc.save(`Dashboard_Report_${date}.pdf`);
};

export default exportDashboardPDF;